# Generated by Django 2.2 on 2019-04-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addhouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=10)),
                ('add_img', models.FileField(upload_to='add_house/img/')),
            ],
        ),
    ]
