# Generated by Django 2.2 on 2019-04-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_addhouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addhouse',
            name='add_img',
        ),
        migrations.AddField(
            model_name='addhouse',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='add_house/img/'),
        ),
    ]
