# Generated by Django 2.2 on 2019-04-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190413_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='addhouse',
            name='sq_feet',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
