# Generated by Django 2.2 on 2019-04-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_addhouse_sq_feet'),
    ]

    operations = [
        migrations.AddField(
            model_name='addhouse',
            name='rupees',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
